title: Fifth
description: A Forth for the Agentic Era
remote_theme: just-the-docs/just-the-docs@v0.10.0
url: https://quivent.github.io
baseurl: /fifth

# Colors
color_scheme: dark

# Aux links (top right)
aux_links:
  GitHub: https://github.com/quivent/fifth
  Homebrew: https://github.com/quivent/homebrew-fifth

# Search
search_enabled: true
search:
  heading_level: 2
  previews: 3

# Navigation
nav_enabled: true

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
